# Generated by Django 6.1.1 on 2026-09-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='door_number',
            field=models.CharField(blank=True, help_text='Door/house number or unit label at the plot (letters, numbers, or text, max 30 characters)', max_length=30),
        ),
    ]
